# Generated by Django 2.0.6 on 2018-10-22 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ADM', 'Administración'), ('ANTR', 'Antropoloía'), ('ARQ', 'Arquitectura'), ('ART', 'Arte'), ('BIO', 'Biología'), ('CPOL', 'Ciencia Política'), ('CONT', 'Contaduría Internacional'), ('DER', 'Derecho'), ('DIS', 'Diseño'), ('ECON', 'Economía'), ('FIL', 'Filosofía'), ('FISI', 'Física'), ('GEO', 'Geociencias'), ('GOB', 'Gobierno y Asuntos Públicos'), ('HIST', 'Historia'), ('HART', 'Historia del Arte'), ('IAM', 'Ingeniería Ambiental'), ('IBIO', 'Ingeniería Biomédica'), ('ICI', 'Ingeniería Civil'), ('ISIS', 'Ingeniería de Sistemas y Computación'), ('IETRI', 'Ingeniería Electrónica'), ('IETRO', 'Ingeniería Electrónica'), ('IIND', 'Ingeniería Industrial'), ('IMEC', 'Ingeniería Mecánica'), ('IQUI', 'Ingeniería Química'), ('LENG', 'Lenguas y Cultura'), ('LART', 'Licenciatura en Artes'), ('LCN', 'Licenciatura en Ciencias Naturales'), ('LCS', 'Licenciatura en Ciencias Sociales'), ('LCEP', 'Licenciatura en Educación para la Primera Infancia'), ('LH', 'Licenciatura en Humanidades'), ('LM', 'Licenciatura en Matemáticas'), ('LIT', 'Lteratura'), ('MAT', 'Matemáticas'), ('MED', 'Medicina'), ('MIC', 'Microbiología'), ('MUS', 'Música'), ('ND', 'Narrativas Digitales'), ('PSI', 'Psicología'), ('QUI', 'Química')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='imagen_perfil')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('imagen', models.ImageField(blank=True, upload_to='imagen_perfil')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Carrera')),
                ('disponibilidad', models.ManyToManyField(to='edushareApp.Horario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='monitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(default='', max_length=200)),
                ('materia', models.CharField(default='', max_length=200)),
                ('tema', models.CharField(default='', max_length=200)),
                ('estiduante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Estudiante')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Monitor')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.ManyToManyField(to='edushareApp.Materia'),
        ),
    ]
