# Generated by Django 2.0.6 on 2018-10-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edushareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('descuento', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('limite', models.IntegerField(default=0)),
                ('fee', models.FloatField(default=0.0)),
                ('cobromaximo', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='disponibilidad',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='monitoria',
            old_name='estiduante',
            new_name='estudiante',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='materias',
        ),
        migrations.AddField(
            model_name='horario',
            name='disponibilidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Carrera'),
        ),
        migrations.AddField(
            model_name='monitoria',
            name='horario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edushareApp.Horario'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(choices=[('ADM', 'Administración'), ('ANTR', 'Antropoloía'), ('ARQ', 'Arquitectura'), ('ART', 'Arte'), ('BIO', 'Biología'), ('CPOL', 'Ciencia Política'), ('CONT', 'Contaduría Internacional'), ('DER', 'Derecho'), ('DIS', 'Diseño'), ('ECON', 'Economía'), ('FIL', 'Filosofía'), ('FISI', 'Física'), ('GEO', 'Geociencias'), ('GOB', 'Gobierno y Asuntos Públicos'), ('HIST', 'Historia'), ('HART', 'Historia del Arte'), ('IAM', 'Ingeniería Ambiental'), ('IBIO', 'Ingeniería Biomédica'), ('ICI', 'Ingeniería Civil'), ('ISIS', 'Ingeniería de Sistemas y Computación'), ('IETRI', 'Ingeniería Electrónica'), ('IETRO', 'Ingeniería Electrónica'), ('IIND', 'Ingeniería Industrial'), ('IMEC', 'Ingeniería Mecánica'), ('IQUI', 'Ingeniería Química'), ('LENG', 'Lenguas y Cultura'), ('LART', 'Licenciatura en Artes'), ('LCN', 'Licenciatura en Ciencias Naturales'), ('LCS', 'Licenciatura en Ciencias Sociales'), ('LCEP', 'Licenciatura en Educación para la Primera Infancia'), ('LH', 'Licenciatura en Humanidades'), ('LM', 'Licenciatura en Matemáticas'), ('LIT', 'Lteratura'), ('MAT', 'Matemáticas'), ('MED', 'Medicina'), ('MIC', 'Microbiología'), ('MUS', 'Música'), ('ND', 'Narrativas Digitales'), ('PSI', 'Psicología'), ('QUI', 'Química')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edushareApp.Categoria'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='edushareApp.Nivel'),
        ),
    ]
